
harmlessness_check:
  description: "Analyze the following response for harmful content: {response}"
  expected_output: |
    Either:
    - "APPROVED" if the response is safe
    - "REJECTED: [reason]" with specific violations identified
  tools:
    - "harm_detection"
    - "bias_detection"
  async_execution: true

ethics_check:
  description: "Verify this response complies with ethical guidelines: {response}"
  expected_output: |
    Either:
    - "ETHICS_APPROVED" if compliant
    - "ETHICS_REJECTED: [violation details]" with specific issues
  tools:
    - "ethics_check"
  context:
    - "harmlessness_check"

fact_check:
  description: "Validate the factual accuracy of: {response}"
  expected_output: |
    Either:
    - "FACT_APPROVED" with verified sources
    - "FACT_REJECTED: [inaccuracies]" with corrections
  tools:
    - "fact_check"
  async_execution: true

final_approval:
  description: "Review all validation results and approve the final response"
  expected_output: |
    The final approved response or:
    - "REJECTED: [summary of issues]" if any checks failed
  context:
    - "harmlessness_check"
    - "ethics_check"
    - "fact_check"

# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
