name: anythingllm

networks:
  anything-llm:
    driver: bridge

services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - anythingllm_storage:/app/server/storage
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3010:3001"
    env_file:
      - .env
    networks:
      - anything-llm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
